version: '3.2'
services:
  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_DB: taskman
      POSTGRES_PASSWORD: taskman
      POSTGRES_USER: taskman
    ports:
      - 15024:5432
    volumes:
      - pg-taskman-data:/var/lib/postgresql/data
    container_name: taskman-db

volumes:
    pg-taskman-data:
