version: '3.2'

services:
  db:
    image:
      postgres:11.5-alpine
    environment:
      POSTGRES_DB: taskman
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    ports:
      - 15024:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    container_name: taskman-db

volumes:
    pg-data:
